
travis_script=_test/xtrabackup.sh
travis_env_global="BRANCH='bb-10.1-marko'"
travis_env_matrix='"MATRIX_CONFIGURE_REST_ENCRYPTION=0","MATRIX_CONFIGURE_REST_ENCRYPTION=1","MATRIX_CONFIGURE_REST_ENCRYPTION=0 MATRIX_CONFIGURE_INNODB_PLUGIN=1","MATRIX_CONFIGURE_REST_ENCRYPTION=1 MATRIX_CONFIGURE_INNODB_PLUGIN=1"'

. travis_build_submit.sh
