
export travis_command="_test/xtrabackup.sh bb-10.1-marko"
export travis_env_matrix='"MATRIX_CONFIGURE_REST_ENCRYPTION=0","MATRIX_CONFIGURE_REST_ENCRYPTION=1","MATRIX_CONFIGURE_REST_ENCRYPTION=0 MATRIX_CONFIGURE_INNODB_PLUGIN=1","MATRIX_CONFIGURE_REST_ENCRYPTION=1 MATRIX_CONFIGURE_INNODB_PLUGIN=1"'

. travis_build_submit.sh
